// Ek detaylar — sürüm, lisans, özellikler, kullanım alanları, temel API açıklamaları, alternatifler
const EXTRA_DETAILS = {
    'express': { version: '4.21', license: 'MIT', features: ['Esnek routing ve middleware mimarisi', 'Binlerce 3. parti middleware', 'RESTful API oluşturma desteği', 'Şablon motoru entegrasyonu', 'Statik dosya sunumu ve hata yönetimi', 'HTTP yardımcı fonksiyonları'], useCases: ['REST API sunucusu', 'Web uygulaması backend', 'Mikroservis', 'SSR'], keyAPIs: [{ n: 'app.get(path, cb)', d: 'GET isteklerini belirtilen path ile eşleştirir' }, { n: 'app.post(path, cb)', d: 'POST isteklerini yakalar, form/veri gönderiminde kullanılır' }, { n: 'app.use(middleware)', d: 'Middleware fonksiyonu ekler, her istekte çalışır' }, { n: 'app.listen(port)', d: 'Sunucuyu belirtilen portta başlatır' }, { n: 'res.json(obj)', d: 'JSON yanıt döner, Content-Type otomatik ayarlanır' }, { n: 'req.params', d: 'URL parametrelerini içeren nesne (/users/:id)' }], alternatives: ['fastify', 'koa', 'hapi'] },

    'lodash': { version: '4.17', license: 'MIT', features: ['200+ yardımcı fonksiyon', 'Performans optimizasyonu yapılmış', 'Modüler yapı', 'Derin klonlama ve merge', 'Fonksiyonel programlama desteği', 'Zincirleme API'], useCases: ['Dizi/nesne dönüşümleri', 'Derin veri birleştirme', 'Veri gruplama', 'Throttle/debounce'], keyAPIs: [{ n: '_.get(obj, path, default)', d: 'İç içe nesneden güvenli değer okur, undefined yerine default döner' }, { n: '_.cloneDeep(obj)', d: 'Nesnenin derin kopyasını oluşturur, referans bağımsız' }, { n: '_.groupBy(arr, key)', d: 'Diziyi belirtilen anahtara göre gruplar' }, { n: '_.debounce(fn, ms)', d: 'Fonksiyonu belirtilen süre sonra bir kez çalıştırır' }, { n: '_.merge(target, ...sources)', d: 'Nesneleri derin birleştirir, iç içe alanları korur' }, { n: '_.flatten(arr)', d: 'İç içe diziyi tek seviyeye düzleştirir' }], alternatives: ['ramda', 'just', 'underscore'] },

    'axios': { version: '1.7', license: 'MIT', features: ['Tarayıcı ve Node.js desteği', 'İstek/yanıt interceptor', 'Otomatik JSON dönüşümü', 'İstek iptal etme', 'İlerleme takibi', 'XSRF koruması'], useCases: ['REST API çağrıları', 'Dosya yükleme/indirme', '3. parti API entegrasyonu', 'SSR veri çekme'], keyAPIs: [{ n: 'axios.get(url, config)', d: 'GET isteği gönderir, sorgu parametreleri config ile eklenir' }, { n: 'axios.post(url, data)', d: 'POST isteği gönderir, data otomatik JSON\'a dönüştürülür' }, { n: 'axios.create(defaults)', d: 'Özel base URL ve header ile yeni instance oluşturur' }, { n: 'interceptors.request.use(fn)', d: 'Her istekten önce çalışan fonksiyon ekler (token ekleme vb.)' }, { n: 'interceptors.response.use(fn)', d: 'Her yanıtta çalışan fonksiyon ekler (hata yönetimi vb.)' }], alternatives: ['node-fetch', 'got', 'ky'] },

    'dotenv': { version: '16.4', license: 'BSD-2', features: ['.env dosyasından ortam değişkeni yükleme', 'Hassas verileri koddan ayırma', 'process.env ile erişim', 'Sıfır bağımlılık', 'TypeScript tipler', 'Çoklu ortam desteği'], useCases: ['API anahtarı yönetimi', 'Veritabanı bağlantı bilgileri', 'Ortam bazlı yapılandırma', 'CI/CD pipeline'], keyAPIs: [{ n: 'dotenv.config()', d: '.env dosyasını okur ve process.env\'e yükler' }, { n: 'dotenv.config({path})', d: 'Özel dosya yolu belirterek farklı .env dosyası yükler' }, { n: 'dotenv.parse(src)', d: 'String/Buffer\'ı ayrıştırır, process.env\'e yazmadan nesne döner' }], alternatives: ['dotenv-expand', 'dotenv-safe', 'env-cmd'] },

    'typescript': { version: '5.6', license: 'Apache-2.0', features: ['Statik tip kontrolü', 'Interface, Generic, Enum', 'Gelişmiş IDE otomatik tamamlama', 'JavaScript ile %100 uyumlu', 'Dekoratör desteği', 'Strict mode'], useCases: ['Büyük ölçekli proje', 'API tip güvenliği', 'Kütüphane geliştirme', 'Takım çalışması'], keyAPIs: [{ n: 'tsc', d: 'TypeScript derleyicisi, .ts dosyalarını .js\'e dönüştürür' }, { n: 'interface User {}', d: 'Nesne yapısını tanımlar, tip kontrolü sağlar' }, { n: 'type Alias = ...', d: 'Tip takma adı oluşturur, union/intersection destekler' }, { n: 'generic<T>', d: 'Yeniden kullanılabilir tip parametresi, koleksiyonlarda yaygın' }, { n: 'tsconfig.json', d: 'Proje derleme ayarları: target, module, strict vb.' }], alternatives: ['flow', 'jsdoc'] },

    'react': { version: '18.3', license: 'MIT', features: ['Virtual DOM ile performans', 'Bileşen tabanlı mimari', 'Hooks API', 'JSX sözdizimi', 'SSR desteği', 'Büyük ekosistem'], useCases: ['SPA', 'Mobil uygulama (React Native)', 'Dashboard', 'E-ticaret arayüzü'], keyAPIs: [{ n: 'useState(initial)', d: 'Bileşen durumu tanımlar, değiştiğinde yeniden render tetikler' }, { n: 'useEffect(fn, deps)', d: 'Yan etki çalıştırır (API çağrısı, DOM manipülasyonu vb.)' }, { n: 'useRef(initial)', d: 'Render arası kalıcı referans tutar, DOM erişimi sağlar' }, { n: 'useContext(ctx)', d: 'Context değerini okur, prop drilling olmadan veri paylaşır' }, { n: 'React.memo(component)', d: 'Props değişmedikçe yeniden render\'ı engeller' }], alternatives: ['vue', 'svelte', 'angular'] },

    'jest': { version: '29.7', license: 'MIT', features: ['Sıfır yapılandırma', 'Snapshot testing', 'Dahili mock ve spy', 'Kod kapsama raporu', 'Paralel test', 'Watch modu'], useCases: ['Unit test', 'Entegrasyon testi', 'Snapshot test', 'API endpoint testi'], keyAPIs: [{ n: 'test(name, fn)', d: 'Bir test case tanımlar, fn içinde assertion yapılır' }, { n: 'expect(val).toBe(x)', d: 'Değerin tam eşitliğini kontrol eder (===)' }, { n: 'expect(val).toEqual(x)', d: 'Derin nesne eşitliğini kontrol eder' }, { n: 'jest.fn()', d: 'Mock fonksiyon oluşturur, çağrı sayısı/argümanları izler' }, { n: 'jest.mock(module)', d: 'Modülü mock\'lar, gerçek kodu çalıştırmadan test eder' }, { n: 'beforeEach(fn)', d: 'Her testten önce çalışır, test ortamını hazırlar' }], alternatives: ['mocha', 'vitest', 'ava'] },

    'mongoose': { version: '8.8', license: 'MIT', features: ['Şema tabanlı modelleme', 'Veri doğrulama', 'Middleware hooks', 'Popülasyon', 'Aggregation pipeline', 'Virtual alanlar'], useCases: ['MongoDB CRUD', 'Veri modelleme', 'Referans ilişkili veri', 'Karmaşık sorgular'], keyAPIs: [{ n: 'new Schema(definition)', d: 'Veri yapısını tanımlar: alanlar, tipler, doğrulama kuralları' }, { n: 'mongoose.model(name, schema)', d: 'Şemadan DB koleksiyonuna bağlı model oluşturur' }, { n: 'Model.find(filter)', d: 'Filtreye uyan tüm belgeleri getirir' }, { n: 'Model.findById(id)', d: 'ID ile tek belge getirir' }, { n: 'doc.save()', d: 'Yeni belge veya değişiklikleri veritabanına kaydeder' }, { n: 'Model.populate(path)', d: 'Referans ID\'leri gerçek belge verileriyle doldurur' }], alternatives: ['prisma', 'typeorm', 'mongodb'] },

    'jsonwebtoken': { version: '9.0', license: 'MIT', features: ['JWT oluşturma ve doğrulama', 'HMAC SHA256 ve RSA', 'Token süresi yönetimi', 'Payload özel veri', 'Stateless auth', 'Refresh token stratejisi'], useCases: ['API kimlik doğrulama', 'Oturum yönetimi', 'Mikroservis iletişimi', 'Şifre sıfırlama linkleri'], keyAPIs: [{ n: 'jwt.sign(payload, secret, opts)', d: 'Yeni JWT oluşturur, expiresIn ile süre belirlenir' }, { n: 'jwt.verify(token, secret)', d: 'Token\'ı doğrular, geçersiz/süresi dolmuşsa hata fırlatır' }, { n: 'jwt.decode(token)', d: 'Token\'ı doğrulama yapmadan çözer (güvenilmeyen veri!)' }], alternatives: ['passport-jwt', 'jose', 'express-jwt'] },

    'nodemon': { version: '3.1', license: 'MIT', features: ['Dosya değişikliklerinde otomatik restart', 'Yapılandırılabilir izleme', 'Uzantı bazlı izleme', 'Gecikme ayarı', 'Özel çalıştırma komutları', '.nodemonignore'], useCases: ['Geliştirme ortamı', 'API sunucu geliştirme', 'Script çalıştırma', 'Prototipleme'], keyAPIs: [{ n: 'nodemon app.js', d: 'app.js dosyasını izler ve değişiklikte yeniden başlatır' }, { n: '--watch src', d: 'Sadece belirtilen dizini izler' }, { n: '--ext js,json', d: 'Sadece belirtilen uzantılardaki değişiklikleri algılar' }, { n: 'nodemon.json', d: 'Proje bazlı yapılandırma dosyası' }], alternatives: ['pm2', 'ts-node-dev', 'tsx'] },

    'cors': { version: '2.8', license: 'MIT', features: ['CORS başlıklarını otomatik yönetme', 'Origin whitelist', 'HTTP method kısıtlama', 'Preflight istek yönetimi', 'Credentials desteği', 'Dinamik origin'], useCases: ['API cross-origin erişimi', 'Frontend-backend ayrı sunucu', '3. parti entegrasyon', 'Mobil API'], keyAPIs: [{ n: 'cors()', d: 'Tüm origin\'lere izin veren varsayılan CORS middleware' }, { n: 'cors({ origin })', d: 'Sadece belirtilen origin\'e izin verir' }, { n: 'cors({ methods })', d: 'İzin verilen HTTP methodlarını kısıtlar' }, { n: 'cors({ credentials: true })', d: 'Cookie/auth header gönderimini etkinleştirir' }], alternatives: ['helmet', 'http-proxy-middleware'] },

    'uuid': { version: '10.0', license: 'MIT', features: ['RFC4122 uyumlu', 'v1, v4, v5 desteği', 'Kriptografik güvenlik', 'Doğrulama fonksiyonu', 'Küçük boyut', 'Çevrimdışı kullanım'], useCases: ['Veritabanı primary key', 'İstek takip ID', 'Dosya isimlendirme', 'Session ID'], keyAPIs: [{ n: 'v4()', d: 'Rastgele UUID oluşturur, en yaygın kullanılan versiyon' }, { n: 'v1()', d: 'Zaman tabanlı UUID, sıralama gereken durumlarda kullanılır' }, { n: 'validate(uuid)', d: 'String\'in geçerli UUID formatında olup olmadığını kontrol eder' }, { n: 'v5(name, namespace)', d: 'İsim ve namespace\'den deterministik UUID üretir' }], alternatives: ['nanoid', 'cuid', 'ulid'] },

    'chalk': { version: '5.3', license: 'MIT', features: ['256 renk ve TrueColor', 'Zincirleme API', 'Arka plan renkleri', 'Hex/RGB desteği', 'Terminal algılama', 'Tagged template literal'], useCases: ['CLI çıktı renklendirme', 'Log mesajları', 'Hata vurgulama', 'İnteraktif terminal'], keyAPIs: [{ n: 'chalk.red(text)', d: 'Metni kırmızı renkte yazdırır' }, { n: 'chalk.bold.green(text)', d: 'Kalın ve yeşil renkte, zincirlenebilir' }, { n: 'chalk.bgBlue.white(text)', d: 'Mavi arka plan üzerine beyaz metin' }, { n: 'chalk.hex("#FF8800")(text)', d: 'Özel hex renk kodu ile metin renklendirme' }, { n: 'chalk.rgb(255,136,0)(text)', d: 'RGB değerleri ile özel renk belirleme' }], alternatives: ['kleur', 'picocolors', 'ansi-colors'] },

    'helmet': { version: '7.2', license: 'MIT', features: ['XSS koruması', 'Clickjacking önleme', 'MIME sniffing engelleme', 'HSTS desteği', 'Referrer Policy', '15+ güvenlik başlığı'], useCases: ['Express güvenlik hardening', 'API güvenliği', 'Web uygulama koruması', 'Compliance'], keyAPIs: [{ n: 'helmet()', d: 'Tüm güvenlik başlıklarını varsayılan ayarlarla etkinleştirir' }, { n: 'helmet.contentSecurityPolicy()', d: 'İçerik güvenlik politikası ayarlar, XSS önler' }, { n: 'helmet.hsts()', d: 'HTTP Strict Transport Security, HTTPS zorunluluğu' }, { n: 'helmet.frameguard()', d: 'Sayfanın iframe içinde yüklenmesini engeller' }], alternatives: ['cors', 'hpp', 'csurf'] },

    'prisma': { version: '5.22', license: 'Apache-2.0', features: ['Şema tabanlı modelleme', 'Otomatik migration', 'TypeScript tam tip güvenliği', 'Sezgisel sorgu API', 'Prisma Studio', 'Çoklu veritabanı'], useCases: ['Veritabanı modelleme', 'CRUD API', 'Veri migration', 'Full-stack TypeScript'], keyAPIs: [{ n: 'prisma.user.create({ data })', d: 'Yeni kayıt oluşturur, data nesnesinde alanlar belirtilir' }, { n: 'prisma.user.findMany({ where })', d: 'Filtreye uyan tüm kayıtları getirir' }, { n: 'prisma.user.update({ where, data })', d: 'Belirtilen kaydı günceller' }, { n: 'prisma.$transaction()', d: 'Birden fazla işlemi atomik olarak çalıştırır' }, { n: 'npx prisma migrate dev', d: 'Şema değişikliklerinden migration oluşturur ve uygular' }], alternatives: ['sequelize', 'typeorm', 'drizzle-orm'] },

    'socket.io': { version: '4.8', license: 'MIT', features: ['WebSocket çift yönlü iletişim', 'Otomatik yeniden bağlanma', 'Oda ve namespace', 'Binary transfer', 'Fallback (long-polling)', 'Redis adapter'], useCases: ['Gerçek zamanlı chat', 'Canlı bildirim', 'Multiplayer oyun', 'Canlı dashboard'], keyAPIs: [{ n: 'io.on("connection", cb)', d: 'Yeni istemci bağlandığında tetiklenir' }, { n: 'socket.emit(event, data)', d: 'İstemciye/sunucuya olay gönderir' }, { n: 'socket.on(event, cb)', d: 'Belirtilen olayı dinler ve callback çalıştırır' }, { n: 'io.to(room).emit()', d: 'Belirli bir odadaki tüm istemcilere mesaj gönderir' }, { n: 'socket.join(room)', d: 'İstemciyi belirtilen odaya ekler' }], alternatives: ['ws', 'pusher', 'ably'] },

    'bcryptjs': { version: '2.4', license: 'MIT', features: ['Güvenli şifre hashleme', 'Otomatik salt oluşturma', 'Ayarlanabilir work factor', 'Async ve sync API', 'Native bağımlılık gerektirmez', 'Timing-safe karşılaştırma'], useCases: ['Kullanıcı şifre saklama', 'Kimlik doğrulama', 'Şifre değiştirme', 'Token hashleme'], keyAPIs: [{ n: 'bcrypt.hash(password, rounds)', d: 'Şifreyi belirtilen round sayısıyla hashler' }, { n: 'bcrypt.compare(password, hash)', d: 'Düz metin şifreyi hash ile karşılaştırır, true/false döner' }, { n: 'bcrypt.genSalt(rounds)', d: 'Belirtilen karmaşıklıkta salt değeri oluşturur' }], alternatives: ['argon2', 'scrypt', 'bcrypt'] },

    'winston': { version: '3.14', license: 'MIT', features: ['Çoklu transport', 'Log seviyeleri', 'Özel formatlar', 'Metadata ekleme', 'Log rotasyonu', 'Asenkron loglama'], useCases: ['Uygulama loglama', 'Hata takibi', 'Audit log', 'Performans izleme'], keyAPIs: [{ n: 'winston.createLogger(opts)', d: 'Logger instance oluşturur, transport ve format ayarları ile' }, { n: 'logger.info(msg, meta)', d: 'Bilgi seviyesinde log yazar, ek metadata eklenebilir' }, { n: 'logger.error(msg, meta)', d: 'Hata seviyesinde log yazar, hata izleme için kritik' }, { n: 'transports.File({ filename })', d: 'Logları dosyaya yazar, level ile filtreleme yapılabilir' }, { n: 'format.combine(...formats)', d: 'Birden fazla formatı birleştirir (timestamp, json vb.)' }], alternatives: ['pino', 'bunyan', 'log4js'] },

    'morgan': { version: '1.10', license: 'MIT', features: ['HTTP istek logları', 'Önceden tanımlı formatlar', 'Özel format string', 'Dosyaya yazma', 'Koşullu loglama', 'Express entegrasyon'], useCases: ['API istek loglama', 'Geliştirme hata ayıklama', 'Erişim log kaydı', 'Performans izleme'], keyAPIs: [{ n: "morgan('dev')", d: 'Renkli kısa format: method, url, status, süre' }, { n: "morgan('combined')", d: 'Apache combined format, üretim ortamı için detaylı log' }, { n: 'morgan({ stream })', d: 'Logları dosyaya veya özel stream\'e yönlendirir' }], alternatives: ['pino-http', 'express-winston'] },

    'multer': { version: '1.4', license: 'MIT', features: ['Multipart dosya yükleme', 'Bellek ve disk depolama', 'Boyut sınırlama', 'MIME filtreleme', 'Çoklu dosya', 'Özel dosya adlandırma'], useCases: ['Profil fotoğrafı yükleme', 'Dosya paylaşım sistemi', 'Toplu dosya işleme', 'Form veri işleme'], keyAPIs: [{ n: 'multer({ dest })', d: 'Dosyaları belirtilen klasöre kaydeden middleware oluşturur' }, { n: 'upload.single(fieldname)', d: 'Tek dosya yükleme, req.file ile erişilir' }, { n: 'upload.array(fieldname, max)', d: 'Çoklu dosya yükleme, req.files dizisi ile erişilir' }, { n: 'multer.diskStorage(opts)', d: 'Dosya adı ve hedef klasörü özelleştiren depolama motoru' }, { n: 'fileFilter(req, file, cb)', d: 'MIME tipine göre dosya kabul/red filtresi' }], alternatives: ['formidable', 'busboy', 'express-fileupload'] },

    'passport': { version: '0.7', license: 'MIT', features: ['500+ strateji', 'Local/OAuth/JWT/SAML', 'Google/Facebook/GitHub', 'Oturum yönetimi', 'Modüler yapı', 'Express uyumlu'], useCases: ['Sosyal login', 'Local kullanıcı girişi', 'JWT API güvenliği', 'Multi-provider auth'], keyAPIs: [{ n: 'passport.use(strategy)', d: 'Kimlik doğrulama stratejisini kaydeder' }, { n: 'passport.authenticate(name)', d: 'Belirtilen strateji ile kimlik doğrulama middleware\'i döner' }, { n: 'passport.serializeUser(fn)', d: 'Kullanıcı nesnesinden session\'a kaydedilecek veriyi belirler' }, { n: 'passport.initialize()', d: 'Passport middleware\'ini Express\'e bağlar' }], alternatives: ['express-session', 'lucia'] },

    'sequelize': { version: '6.37', license: 'MIT', features: ['Promise tabanlı ORM', 'Migration ve seeder', 'Eager/lazy loading', 'Transaction yönetimi', 'Raw SQL desteği', 'Çoklu veritabanı'], useCases: ['İlişkisel veritabanı ORM', 'CRUD API', 'Veritabanı migration', 'Kompleks sorgular'], keyAPIs: [{ n: 'sequelize.define(name, attrs)', d: 'Model tanımlar, sütun tipleri ve kısıtlamalar belirtilir' }, { n: 'Model.findAll({ where })', d: 'Koşula uyan tüm kayıtları getirir' }, { n: 'Model.create(data)', d: 'Yeni kayıt oluşturur ve veritabanına kaydeder' }, { n: 'sequelize.transaction(fn)', d: 'İşlemi transaction içinde çalıştırır, hata olursa rollback' }, { n: 'Model.belongsTo(OtherModel)', d: 'İki model arasında ilişki tanımlar (1:1, 1:N, N:M)' }], alternatives: ['prisma', 'typeorm', 'drizzle-orm'] },

    'zod': { version: '3.23', license: 'MIT', features: ['TypeScript-first tasarım', 'Otomatik tip çıkarımı', 'Zincirleme doğrulama', 'Transform desteği', 'Detaylı hata mesajları', 'JSON Schema dönüşümü'], useCases: ['API istek doğrulama', 'Form validasyonu', 'Çevre değişkeni doğrulama', 'Konfigürasyon şeması'], keyAPIs: [{ n: 'z.string().email()', d: 'String doğrulama, email formatı zorunlu' }, { n: 'z.object({ ... })', d: 'Nesne şeması tanımlar, her alan ayrı doğrulanır' }, { n: 'schema.parse(data)', d: 'Veriyi doğrular, geçersizse ZodError fırlatır' }, { n: 'schema.safeParse(data)', d: 'Doğrular ama hata fırlatmaz, {success, data/error} döner' }, { n: 'z.infer<typeof schema>', d: 'Şemadan TypeScript tipini otomatik çıkarır' }], alternatives: ['joi', 'yup', 'valibot'] },

    'dayjs': { version: '1.11', license: 'MIT', features: ['Sadece 2KB', 'Moment.js uyumlu API', 'Immutable yapı', 'Eklenti sistemi', 'Yerelleştirme (Türkçe)', 'Timezone eklentisi'], useCases: ['Tarih formatlama', 'Göreceli zaman', 'Tarih hesaplama', 'Zaman dilimi dönüşümü'], keyAPIs: [{ n: 'dayjs()', d: 'Şu anki tarih/saat ile yeni instance oluşturur' }, { n: 'dayjs().format(template)', d: 'Tarihi belirtilen formatta string\'e dönüştürür' }, { n: 'dayjs().add(value, unit)', d: 'Tarihe gün/ay/yıl ekler, yeni instance döner' }, { n: 'dayjs().diff(other, unit)', d: 'İki tarih arasındaki farkı hesaplar' }, { n: 'dayjs().fromNow()', d: 'Göreli zaman döner: "2 saat önce" gibi' }], alternatives: ['date-fns', 'luxon', 'moment'] },

    'commander': { version: '12.1', license: 'MIT', features: ['Komut ve alt komut tanımlama', 'Seçenek ayrıştırma', 'Otomatik --help', '--version desteği', 'Tip dönüşümü', 'Hata yönetimi'], useCases: ['CLI araç geliştirme', 'Script otomasyonu', 'Geliştirici araçları', 'DevOps komutları'], keyAPIs: [{ n: 'program.command(name)', d: 'Yeni alt komut tanımlar' }, { n: 'program.option(flags, desc)', d: 'Komut satırı seçeneği ekler (-p, --port gibi)' }, { n: 'program.argument(name)', d: 'Zorunlu veya opsiyonel pozisyonel argüman ekler' }, { n: 'program.action(fn)', d: 'Komut çalıştırıldığında tetiklenecek fonksiyonu belirler' }, { n: 'program.parse()', d: 'process.argv\'yi ayrıştırır ve ilgili komutu çalıştırır' }], alternatives: ['yargs', 'meow', 'cac'] },

    'fastify': { version: '5.1', license: 'MIT', features: ['Express\'ten 2-3x hızlı', 'JSON Schema doğrulama', 'Otomatik Swagger', 'Eklenti mimarisi', 'TypeScript-first', 'Async/await native'], useCases: ['Yüksek performanslı API', 'Mikroservis', 'REST API', 'GraphQL API'], keyAPIs: [{ n: 'fastify.get(path, handler)', d: 'GET route tanımlar, handler async olabilir' }, { n: 'fastify.register(plugin)', d: 'Eklenti ekler, kapsüllenmiş context sağlar' }, { n: 'fastify.listen({ port })', d: 'Sunucuyu başlatır' }, { n: 'reply.send(data)', d: 'Yanıt gönderir, JSON otomatik serialize edilir' }, { n: 'schema: { body }', d: 'JSON Schema ile otomatik istek doğrulama' }], alternatives: ['express', 'koa', 'hapi'] },

    'nodemailer': { version: '6.9', license: 'MIT', features: ['SMTP ve OAuth2', 'HTML ve düz metin', 'Dosya ekleri', 'Şablon motoru', 'DKIM imzalama', 'Connection pooling'], useCases: ['Bildirim e-postası', 'Şifre sıfırlama maili', 'Toplu e-posta', 'Otomatik rapor'], keyAPIs: [{ n: 'nodemailer.createTransport(opts)', d: 'SMTP bağlantısı oluşturur, host/port/auth ayarları' }, { n: 'transporter.sendMail(msg)', d: 'E-posta gönderir: from, to, subject, html alanları' }, { n: 'transporter.verify()', d: 'SMTP bağlantısının çalışıp çalışmadığını test eder' }], alternatives: ['sendgrid', 'mailgun', 'aws-ses'] },

    'sharp': { version: '0.33', license: 'Apache-2.0', features: ['libvips tabanlı yüksek performans', 'Resize, crop, rotate', 'JPEG/PNG/WebP/AVIF', 'Metadata okuma', 'Stream API', 'ImageMagick\'ten 4-5x hızlı'], useCases: ['Thumbnail oluşturma', 'Resim optimizasyonu', 'Format dönüşümü', 'Watermark ekleme'], keyAPIs: [{ n: 'sharp(input)', d: 'Resim işleme pipeline\'ı başlatır, dosya/buffer kabul eder' }, { n: '.resize(w, h, opts)', d: 'Boyutlandırır, fit: cover/contain/fill seçenekleri' }, { n: '.webp({ quality })', d: 'WebP formatına dönüştürür, kalite 1-100 arası' }, { n: '.toFile(path)', d: 'Sonucu dosyaya kaydeder' }, { n: '.toBuffer()', d: 'Sonucu Buffer olarak döner, stream işlemler için' }], alternatives: ['jimp', 'gm', 'image-size'] },

    'puppeteer': { version: '23.7', license: 'Apache-2.0', features: ['Headless Chrome kontrolü', 'Web scraping', 'PDF/screenshot', 'Form otomasyonu', 'Network yakalama', 'Performans profiling'], useCases: ['Web scraping', 'E2E test', 'PDF rapor', 'Sosyal medya otomasyon'], keyAPIs: [{ n: 'puppeteer.launch(opts)', d: 'Chromium tarayıcı başlatır, headless: true/false' }, { n: 'page.goto(url)', d: 'Belirtilen URL\'ye gider, sayfa yüklenene kadar bekler' }, { n: 'page.click(selector)', d: 'CSS seçici ile elementi tıklar' }, { n: 'page.type(selector, text)', d: 'Input alanına metin yazar' }, { n: 'page.screenshot({ path })', d: 'Sayfanın ekran görüntüsünü alır' }, { n: 'page.evaluate(fn)', d: 'Tarayıcı kontekstinde JavaScript çalıştırır' }], alternatives: ['playwright', 'selenium', 'cypress'] },

    'fs-extra': { version: '11.2', license: 'MIT', features: ['Rekursif kopyalama/taşıma', 'ensureDir ile güvenli dizin', 'JSON okuma/yazma', 'Promise tabanlı', 'Node.js fs dahil', 'Atomik yazma'], useCases: ['Build script', 'Dosya yönetimi', 'Proje scaffolding', 'Backup/restore'], keyAPIs: [{ n: 'fs.copy(src, dest)', d: 'Dosya/dizini hedefine kopyalar, recursive varsayılan' }, { n: 'fs.ensureDir(path)', d: 'Dizini oluşturur, varsa hata vermez (mkdir -p gibi)' }, { n: 'fs.readJson(path)', d: 'JSON dosyasını okur ve otomatik parse eder' }, { n: 'fs.writeJson(path, obj)', d: 'Nesneyi JSON olarak dosyaya yazar' }, { n: 'fs.remove(path)', d: 'Dosya veya dizini recursive siler' }, { n: 'fs.pathExists(path)', d: 'Yolun var olup olmadığını kontrol eder, boolean döner' }], alternatives: ['graceful-fs', 'mkdirp', 'rimraf'] },

    'joi': { version: '17.13', license: 'BSD-3', features: ['Kapsamlı doğrulama kuralları', 'Koşullu doğrulama', 'Özel doğrulama fonksiyonları', 'Çevrilebilir hata mesajları', 'Tip dönüşümü', 'Binary doğrulama'], useCases: ['API istek doğrulama', 'Form validasyonu', 'Konfigürasyon doğrulama', 'Veri temizleme'], keyAPIs: [{ n: 'Joi.string().email()', d: 'String tipinde, geçerli email formatı zorunlu' }, { n: 'Joi.number().min(n).max(n)', d: 'Sayı, minimum ve maksimum aralık belirleme' }, { n: 'Joi.object({ ... })', d: 'Nesne şeması, her alan ayrı doğrulanır' }, { n: 'schema.validate(data)', d: 'Veriyi doğrular, {error, value} nesnesi döner' }, { n: 'Joi.alternatives()', d: 'Birden fazla şemadan birinin geçerli olmasını sağlar' }], alternatives: ['zod', 'yup', 'ajv'] },

    'inquirer': { version: '10.2', license: 'MIT', features: ['Input, select, checkbox, confirm', 'Liste ve tablo seçimi', 'Doğrulama ve filtreleme', 'Koşullu sorular', 'Özel temalar', 'Pagination'], useCases: ['CLI wizard', 'İnteraktif kurulum', 'Proje scaffolding', 'Konfigürasyon sihirbazı'], keyAPIs: [{ n: 'input({ message })', d: 'Kullanıcıdan metin girişi alır' }, { n: 'select({ choices })', d: 'Listeden tek seçim yaptırır' }, { n: 'checkbox({ choices })', d: 'Çoklu seçim listesi sunar' }, { n: 'confirm({ message })', d: 'Evet/hayır sorusu sorar, boolean döner' }, { n: 'password({ message })', d: 'Gizli şifre girişi alır, karakterler maskelenir' }], alternatives: ['prompts', 'enquirer', 'clack'] },

    'webpack': { version: '5.96', license: 'MIT', features: ['Module bundling', 'Code splitting', 'Tree shaking', 'HMR', 'Loader/plugin ekosistemi', 'Asset modülleri'], useCases: ['SPA bundling', 'Kütüphane geliştirme', 'Çoklu giriş noktası', 'Micro-frontend'], keyAPIs: [{ n: 'entry', d: 'Uygulamanın giriş noktası dosyası' }, { n: 'output.filename', d: 'Çıktı bundle dosya adı ve yolu' }, { n: 'module.rules', d: 'Loader kuralları: CSS, resim, font vb. dosya işleme' }, { n: 'plugins', d: 'HtmlWebpackPlugin, MiniCssExtractPlugin vb. eklentiler' }, { n: 'optimization.splitChunks', d: 'Ortak kodu ayrı chunk\'lara böler, cache verimliliği' }], alternatives: ['vite', 'esbuild', 'rollup'] },

    'body-parser': { version: '1.20', license: 'MIT', features: ['JSON gövde ayrıştırma', 'URL-encoded form', 'Raw/text gövde', 'Boyut sınırlama', 'Özel medya tipi', 'Express dahili'], useCases: ['REST API gövde ayrıştırma', 'Form veri işleme', 'Webhook işleme', 'Raw veri alma'], keyAPIs: [{ n: 'express.json()', d: 'JSON gövdelerini ayrıştırır, req.body olarak erişilir' }, { n: 'express.urlencoded({ extended })', d: 'Form verilerini ayrıştırır, extended: true iç içe nesne destekler' }, { n: 'bodyParser.raw()', d: 'Ham binary veriyi Buffer olarak alır' }, { n: '{ limit: "10mb" }', d: 'Maksimum gövde boyutunu sınırlar' }], alternatives: ['express.json()', 'express.urlencoded()'] },

    'cheerio': { version: '1.0', license: 'MIT', features: ['jQuery benzeri HTML API', 'Sunucu tarafı DOM', 'CSS seçici desteği', 'HTML manipülasyon', 'Hafif ve hızlı', 'XML ayrıştırma'], useCases: ['Web scraping', 'HTML ayrıştırma', 'E-posta şablonu', 'SEO analizi'], keyAPIs: [{ n: 'cheerio.load(html)', d: 'HTML string\'den DOM ağacı oluşturur, $ fonksiyonu döner' }, { n: '$(selector)', d: 'CSS seçici ile element seçer, jQuery gibi' }, { n: '$(el).text()', d: 'Elementin metin içeriğini döner' }, { n: '$(el).attr(name)', d: 'Elementin belirtilen attribute değerini döner' }, { n: '$(el).find(selector)', d: 'Alt elementler arasında seçici ile arama yapar' }, { n: '$(el).each(fn)', d: 'Bulunan her element için fonksiyon çalıştırır' }], alternatives: ['puppeteer', 'jsdom', 'htmlparser2'] },

    'node-cron': { version: '3.0', license: 'ISC', features: ['Cron sözdizimi', 'Saniye hassasiyeti', 'Timezone desteği', 'Başlatma/durdurma', 'Validate fonksiyonu', 'Çoklu görev'], useCases: ['Zamanlanmış görevler', 'Veritabanı temizleme', 'Rapor gönderimi', 'Cache yenileme'], keyAPIs: [{ n: 'cron.schedule(expr, fn)', d: 'Cron ifadesine göre tekrarlayan görev oluşturur' }, { n: 'task.start()', d: 'Durdurulmuş görevi yeniden başlatır' }, { n: 'task.stop()', d: 'Çalışan görevi durdurur' }, { n: 'cron.validate(expr)', d: 'Cron ifadesinin geçerli olup olmadığını kontrol eder' }], alternatives: ['agenda', 'bull', 'bree'] },

    'express-validator': { version: '7.2', license: 'MIT', features: ['Zincirleme doğrulama', 'Sanitization', 'Özel hata mesajları', 'Query/body/params', 'Özel kurallar', 'Schema tabanlı'], useCases: ['Form doğrulama', 'API giriş kontrolü', 'XSS önleme', 'Veri temizleme'], keyAPIs: [{ n: 'body(field).isEmail()', d: 'Request body alanını email formatında doğrular' }, { n: 'query(field).isInt()', d: 'Query parametresini integer olarak doğrular' }, { n: 'validationResult(req)', d: 'Tüm doğrulama hatalarını toplar ve döner' }, { n: '.withMessage(msg)', d: 'Doğrulama hatasına özel Türkçe mesaj ekler' }, { n: 'checkSchema(schema)', d: 'Nesne tabanlı toplu doğrulama şeması tanımlar' }], alternatives: ['joi', 'zod', 'class-validator'] },

    'ejs': { version: '3.1', license: 'Apache-2.0', features: ['HTML içinde JavaScript', 'Basit sözdizimi', 'Include ile partial', 'Layout desteği', 'Ön derleme', 'Express entegrasyon'], useCases: ['Sunucu taraflı render', 'E-posta şablonu', 'PDF şablonu', 'Statik site oluşturma'], keyAPIs: [{ n: '<%= expr %>', d: 'İfadeyi HTML-escaped olarak yazdırır (XSS güvenli)' }, { n: '<%- html %>', d: 'HTML\'i escape etmeden yazdırır (güvenilir veri için)' }, { n: '<% code %>', d: 'JavaScript kodu çalıştırır, çıktı üretmez' }, { n: '<%- include(path) %>', d: 'Başka bir EJS dosyasını dahil eder (partial)' }, { n: 'ejs.renderFile(path, data)', d: 'Dosyayı veri ile render ederek HTML string döner' }], alternatives: ['pug', 'handlebars', 'nunjucks'] },

    'pino': { version: '9.5', license: 'MIT', features: ['Winston\'dan 5x hızlı', 'JSON log', 'Child logger', 'Redaction', 'Transport sistemi', 'pino-pretty'], useCases: ['Yüksek trafikli uygulama', 'Mikroservis log', 'JSON log pipeline', 'ELK entegrasyon'], keyAPIs: [{ n: 'pino(opts)', d: 'Logger instance oluşturur, level ve transport ayarları' }, { n: 'logger.info(msg)', d: 'Bilgi seviyesinde JSON log yazar' }, { n: 'logger.child({ module })', d: 'Alt modül için kontekstli child logger oluşturur' }, { n: 'pino.transport({ target })', d: 'Log çıktısını dosya, pretty-print veya özel hedefe yönlendirir' }, { n: 'logger.error({ err }, msg)', d: 'Hata nesnesini serialize ederek log yazar' }], alternatives: ['winston', 'bunyan', 'roarr'] },

    'got': { version: '14.4', license: 'MIT', features: ['Promise tabanlı modern API', 'Otomatik retry', 'Stream ve pagination', 'Cache mekanizması', 'Timeout/iptal', 'Hook sistemi'], useCases: ['API çağrıları', 'Dosya indirme', 'Web scraping', 'Webhook gönderimi'], keyAPIs: [{ n: 'got(url, opts)', d: 'HTTP isteği gönderir, varsayılan GET' }, { n: 'got.post(url, { json })', d: 'JSON body ile POST isteği gönderir' }, { n: 'got.stream(url)', d: 'Yanıtı stream olarak alır, büyük dosyalar için' }, { n: 'got.paginate(url)', d: 'Sayfalanmış API yanıtlarını otomatik iterasyon ile alır' }, { n: 'got.extend(defaults)', d: 'Özel varsayılanlarla yeni got instance oluşturur' }], alternatives: ['axios', 'node-fetch', 'undici'] },

    'pg': { version: '8.13', license: 'MIT', features: ['PostgreSQL resmi sürücü', 'Connection pooling', 'Prepared statement', 'LISTEN/NOTIFY', 'COPY API', 'SSL/TLS'], useCases: ['PostgreSQL CRUD', 'Gelişmiş SQL', 'Gerçek zamanlı veri', 'Toplu veri aktarımı'], keyAPIs: [{ n: 'new Pool(config)', d: 'Bağlantı havuzu oluşturur, max bağlantı sayısı ayarlanır' }, { n: 'pool.query(sql, params)', d: 'Parametreli SQL sorgusu çalıştırır, SQL injection önler' }, { n: 'pool.connect()', d: 'Havuzdan tek bir bağlantı alır, transaction için gerekli' }, { n: 'client.release()', d: 'Kullanılan bağlantıyı havuza geri bırakır' }, { n: 'client.query("BEGIN")', d: 'Transaction başlatır, COMMIT/ROLLBACK ile sonlanır' }], alternatives: ['mysql2', 'better-sqlite3', 'postgres'] },

    'vite': { version: '6.0', license: 'MIT', features: ['esbuild ile anında dev sunucu', 'Native ESM HMR', 'Rollup production build', 'CSS Modules/PostCSS', 'TypeScript/JSX native', 'Zengin eklenti'], useCases: ['Frontend proje', 'React/Vue/Svelte', 'Kütüphane geliştirme', 'SSR'], keyAPIs: [{ n: 'npm create vite@latest', d: 'Yeni Vite projesi oluşturur, framework seçimi sunar' }, { n: 'defineConfig({})', d: 'vite.config.js içinde tip güvenli yapılandırma' }, { n: 'import.meta.env.VITE_*', d: 'Çevre değişkenlerine istemci tarafında erişim' }, { n: 'vite dev', d: 'Geliştirme sunucusunu başlatır, HMR aktif' }, { n: 'vite build', d: 'Üretim için optimize edilmiş bundle oluşturur' }], alternatives: ['webpack', 'parcel', 'turbopack'] },

    'knex': { version: '3.1', license: 'MIT', features: ['SQL query builder', 'Migration/seeder', 'Transaction yönetimi', 'Zincirleme API', 'Raw SQL', 'Çoklu veritabanı'], useCases: ['SQL sorgu oluşturma', 'Veritabanı migration', 'Kompleks JOIN', 'Veri raporlama'], keyAPIs: [{ n: 'knex(table).select()', d: 'SELECT sorgusu oluşturur, zincirleme filtreler eklenebilir' }, { n: '.where(column, value)', d: 'WHERE koşulu ekler, eşitlik kontrolü' }, { n: '.insert(data)', d: 'INSERT sorgusu, nesne veya dizi kabul eder' }, { n: 'knex.migrate.latest()', d: 'Bekleyen tüm migration\'ları çalıştırır' }, { n: 'knex.raw(sql, bindings)', d: 'Ham SQL çalıştırır, parametre bağlama ile güvenli' }], alternatives: ['prisma', 'sequelize', 'drizzle-orm'] },

    'express-rate-limit': { version: '7.4', license: 'MIT', features: ['IP bazlı sınırlama', 'Özel zaman penceresi', 'Redis/bellek store', 'Brute-force koruması', 'Rate-limit başlıkları', 'Skip fonksiyonu'], useCases: ['API rate limiting', 'Login brute-force koruması', 'DDoS azaltma', 'Public API limitleme'], keyAPIs: [{ n: 'rateLimit({ windowMs, max })', d: 'Rate limiter oluşturur, windowMs sürede max istek' }, { n: 'windowMs', d: 'Zaman penceresi (ms), örn: 15*60*1000 = 15 dakika' }, { n: 'max', d: 'Pencere içinde IP başına izin verilen maksimum istek sayısı' }, { n: 'message', d: 'Limit aşıldığında dönen hata mesajı/nesnesi' }, { n: 'skip(req)', d: 'Belirli istekleri limitleme dışı bırakır (admin vb.)' }], alternatives: ['rate-limiter-flexible', 'express-brute'] },

    'mocha': { version: '10.8', license: 'MIT', features: ['BDD ve TDD arayüzü', 'Esnek reporter', 'before/after hooks', 'Asenkron test', 'Tarayıcı desteği', 'Retry'], useCases: ['Unit test', 'Entegrasyon testi', 'API testi', 'TDD/BDD geliştirme'], keyAPIs: [{ n: 'describe(name, fn)', d: 'Test grubunu tanımlar, iç içe kullanılabilir' }, { n: 'it(name, fn)', d: 'Tek bir test case tanımlar' }, { n: 'before(fn)', d: 'Gruptaki tüm testlerden önce bir kez çalışır' }, { n: 'beforeEach(fn)', d: 'Her testten önce çalışır, ortamı sıfırlar' }, { n: 'after(fn)', d: 'Tüm testler bittikten sonra çalışır, temizlik yapar' }], alternatives: ['jest', 'vitest', 'ava'] },

    'glob': { version: '11.0', license: 'ISC', features: ['Shell dosya kalıbı eşleştirme', '** ile recursive', 'Ignore kalıpları', 'Sync/async API', 'Yüksek performans', 'POSIX normalizasyon'], useCases: ['Build script dosya toplama', 'Test dosyası bulma', 'Toplu dosya işleme', 'Lint hedef belirleme'], keyAPIs: [{ n: 'glob(pattern)', d: 'Kalıba uyan dosya yollarını döner (async)' }, { n: 'globSync(pattern)', d: 'Senkron versiyon, küçük projeler için' }, { n: '"**/*.js"', d: 'Tüm alt dizinlerdeki JS dosyalarını eşleştirir' }, { n: '{ ignore: [...] }', d: 'Belirtilen kalıpları sonuçtan hariç tutar' }], alternatives: ['fast-glob', 'globby', 'picomatch'] },

    'ioredis': { version: '5.4', license: 'MIT', features: ['Redis Cluster ve Sentinel', 'Pipeline', 'Lua script', 'Stream API', 'Otomatik reconnect', 'Pub/Sub'], useCases: ['Cache yönetimi', 'Session store', 'Mesaj kuyruğu', 'Rate limiting'], keyAPIs: [{ n: 'new Redis(url)', d: 'Redis bağlantısı oluşturur, URL veya config nesnesi' }, { n: 'redis.set(key, value)', d: 'Anahtar-değer çifti kaydeder' }, { n: 'redis.get(key)', d: 'Anahtara karşılık gelen değeri okur' }, { n: 'redis.setex(key, ttl, val)', d: 'TTL (saniye) ile otomatik süresi dolan kayıt oluşturur' }, { n: 'redis.pipeline()', d: 'Birden fazla komutu batch olarak gönderir, performans artışı' }], alternatives: ['redis', 'connect-redis'] },

    'compression': { version: '1.7', license: 'MIT', features: ['gzip/deflate sıkıştırma', 'Eşik boyutu', 'Medya tipi filtreleme', 'Bant genişliği tasarrufu', 'Express uyumlu', 'Level yapılandırma'], useCases: ['API yanıt sıkıştırma', 'Statik dosya sıkıştırma', 'Bant genişliği optimizasyonu'], keyAPIs: [{ n: 'compression()', d: 'Varsayılan ayarlarla sıkıştırma middleware oluşturur' }, { n: '{ threshold: 1024 }', d: '1KB altındaki yanıtları sıkıştırmaz' }, { n: '{ level: 6 }', d: 'Sıkıştırma seviyesi 1-9, yüksek = daha küçük ama yavaş' }], alternatives: ['shrink-ray-current'] },

    'supertest': { version: '7.0', license: 'MIT', features: ['HTTP assertion testi', 'Sunucusuz test', 'Zincirleme assertion', 'Header/status/body kontrolü', 'Cookie/auth desteği', 'Jest/Mocha entegrasyon'], useCases: ['API endpoint testi', 'Express route testi', 'Middleware testi', 'CI/CD pipeline'], keyAPIs: [{ n: 'request(app)', d: 'Express app ile test instance oluşturur, sunucu başlatmaz' }, { n: '.get(path)', d: 'GET isteği gönderir' }, { n: '.expect(statusCode)', d: 'Yanıt HTTP status kodunu doğrular' }, { n: '.expect("Content-Type", /json/)', d: 'Yanıt header değerini regex ile doğrular' }, { n: '.send(body)', d: 'İstek body\'si gönderir (POST/PUT için)' }], alternatives: ['chai-http', 'pactum', 'frisby'] },

    'cookie-parser': { version: '1.4', license: 'MIT', features: ['HTTP çerez ayrıştırma', 'İmzalı çerez', 'JSON çerez', 'Çerez seçenekleri', 'Express uyumlu', 'Güvenli yönetim'], useCases: ['Çerez tabanlı oturum', 'Tercih saklama', 'CSRF token', 'Analitik takip'], keyAPIs: [{ n: 'cookieParser(secret)', d: 'Cookie parser middleware, secret ile imzalı çerezleri doğrular' }, { n: 'req.cookies', d: 'İstemciden gelen tüm çerezleri içeren nesne' }, { n: 'req.signedCookies', d: 'İmzası doğrulanmış çerezleri içeren nesne' }, { n: 'res.cookie(name, val, opts)', d: 'Yanıta yeni çerez ekler, maxAge/httpOnly/secure ayarları' }], alternatives: ['express-session', 'cookie-session'] },

    'chokidar': { version: '4.0', license: 'MIT', features: ['Güvenilir dosya izleme', 'Platformlar arası', 'Glob kalıp desteği', 'Debounce', 'Ready olayı', 'Atomic write algılama'], useCases: ['Build araçları', 'Dev sunucu', 'Dosya senkronizasyon', 'Hot reload'], keyAPIs: [{ n: 'chokidar.watch(paths, opts)', d: 'Dosya/dizin izlemeye başlar, glob destekler' }, { n: '.on("change", cb)', d: 'Dosya değiştiğinde tetiklenir, path argümanı verir' }, { n: '.on("add", cb)', d: 'Yeni dosya eklendiğinde tetiklenir' }, { n: '.on("unlink", cb)', d: 'Dosya silindiğinde tetiklenir' }, { n: 'watcher.close()', d: 'İzlemeyi durdurur ve kaynakları serbest bırakır' }], alternatives: ['watchpack', 'fb-watchman'] },

    'ws': { version: '8.18', license: 'MIT', features: ['En hızlı WebSocket kütüphanesi', 'Binary mesaj', 'Ping/pong', 'Sıkıştırma', 'Stream API', 'İstemci ve sunucu'], useCases: ['Gerçek zamanlı uygulama', 'Chat sunucusu', 'Canlı veri akışı', 'IoT bağlantısı'], keyAPIs: [{ n: 'new WebSocket.Server({ port })', d: 'WebSocket sunucu oluşturur, belirtilen portta dinler' }, { n: 'wss.on("connection", cb)', d: 'Yeni istemci bağlandığında tetiklenir' }, { n: 'ws.send(data)', d: 'İstemciye mesaj gönderir, string veya buffer' }, { n: 'ws.on("message", cb)', d: 'İstemciden gelen mesajları dinler' }, { n: 'ws.close()', d: 'Bağlantıyı kapatır' }], alternatives: ['socket.io', 'faye-websocket'] },

    'ora': { version: '8.1', license: 'MIT', features: ['Şık terminal spinner', 'Farklı spinner stilleri', 'Başarı/hata durumu', 'Renk desteği', 'Promise entegrasyon', 'Metin güncelleme'], useCases: ['CLI yükleme göstergesi', 'Asenkron işlem takibi', 'Kurulum scripti', 'Deploy aracı'], keyAPIs: [{ n: 'ora(text).start()', d: 'Spinner başlatır, metin ile birlikte gösterir' }, { n: 'spinner.succeed(text)', d: 'Yeşil ✔ ile başarı durumuna geçer' }, { n: 'spinner.fail(text)', d: 'Kırmızı ✖ ile hata durumuna geçer' }, { n: 'spinner.text = "..."', d: 'Spinner metnini dinamik olarak günceller' }, { n: 'spinner.stop()', d: 'Spinner\'ı durdurur ve siler' }], alternatives: ['cli-spinners', 'log-update', 'listr2'] },

    'yargs': { version: '17.7', license: 'MIT', features: ['Komut tabanlı CLI', 'Tip kontrolü', 'Otomatik yardım', 'Bash tamamlama', 'Middleware', 'Lokalizasyon'], useCases: ['CLI araç geliştirme', 'Script parametre yönetimi', 'DevOps araçları', 'Build komutları'], keyAPIs: [{ n: 'yargs.command(cmd, desc, builder, handler)', d: 'Alt komut tanımlar, kendi argüman/seçenekleri olabilir' }, { n: '.option(key, opts)', d: 'Komut satırı seçeneği ekler, tip ve varsayılan belirtilir' }, { n: '.positional(key, opts)', d: 'Pozisyonel argüman tanımlar' }, { n: '.demandOption(key)', d: 'Seçeneği zorunlu kılar, yoksa hata verir' }, { n: '.parse()', d: 'Argümanları ayrıştırır ve nesne olarak döner' }], alternatives: ['commander', 'meow', 'cac'] },

    'express-session': { version: '1.18', license: 'MIT', features: ['Sunucu taraflı oturum', 'Redis/Mongo store', 'Çerez yapılandırma', 'Oturum süresi', 'Rolling session', 'Trust proxy'], useCases: ['Kullanıcı oturumu', 'Sepet yönetimi', 'Form wizard', 'CSRF koruması'], keyAPIs: [{ n: 'session({ secret, ... })', d: 'Session middleware oluşturur, secret ile cookie imzalanır' }, { n: 'req.session.user', d: 'Session nesnesine veri okuma/yazma' }, { n: 'req.session.destroy(cb)', d: 'Mevcut oturumu sonlandırır ve siler' }, { n: 'req.session.regenerate(cb)', d: 'Yeni session ID oluşturur, güvenlik için önemli' }, { n: 'store: new RedisStore()', d: 'Oturumları Redis gibi harici depoda saklar' }], alternatives: ['cookie-session', 'passport', 'express-jwt'] },

    'pug': { version: '3.0', license: 'MIT', features: ['Girinti tabanlı temiz sözdizimi', 'Mixin ve include', 'Template kalıtımı', 'Filtreler', 'Ön derleme', 'Express uyumlu'], useCases: ['Sunucu taraflı HTML', 'E-posta şablonu', 'Statik site üretici', 'Prototip UI'], keyAPIs: [{ n: 'pug.renderFile(path, data)', d: 'PUG dosyasını render eder, HTML string döner' }, { n: 'extends layout', d: 'Başka bir şablonu temel alır (kalıtım)' }, { n: 'block content', d: 'Kalıtımda doldurulacak alan tanımlar' }, { n: 'include partial', d: 'Başka bir PUG dosyasını dahil eder' }, { n: 'mixin name(args)', d: 'Yeniden kullanılabilir bileşen tanımlar' }], alternatives: ['ejs', 'handlebars', 'nunjucks'] },

    'bull': { version: '4.16', license: 'MIT', features: ['Redis tabanlı kuyruk', 'Gecikmeli işler', 'Tekrarlayan görevler', 'Öncelik sırası', 'Eşzamanlılık kontrolü', 'Dashboard (Arena/Board)'], useCases: ['E-posta kuyruğu', 'Resim işleme', 'Rapor oluşturma', 'Bildirim gönderimi'], keyAPIs: [{ n: 'new Queue(name, redisUrl)', d: 'Yeni kuyruk oluşturur, Redis bağlantısı ile' }, { n: 'queue.add(data, opts)', d: 'Kuyruğa iş ekler, delay ve priority ayarlanabilir' }, { n: 'queue.process(fn)', d: 'İşçi tanımlar, kuyruktan iş geldiğinde çalıştırır' }, { n: 'job.progress(percent)', d: 'İş ilerlemesini günceller' }, { n: 'queue.on("completed", cb)', d: 'İş tamamlandığında tetiklenir' }], alternatives: ['bullmq', 'agenda', 'bee-queue'] },

    'handlebars': { version: '4.7', license: 'MIT', features: ['Mustache uyumlu', 'Helper fonksiyonlar', 'Partial şablonlar', 'Block ifadeler', 'Ön derleme', 'Strict mode'], useCases: ['E-posta şablonu', 'PDF şablonu', 'CMS içerik', 'Statik site'], keyAPIs: [{ n: 'Handlebars.compile(template)', d: 'Şablon stringini fonksiyona derler' }, { n: 'template(context)', d: 'Derlenen şablonu veri ile render eder, HTML döner' }, { n: 'Handlebars.registerHelper(name, fn)', d: 'Özel helper fonksiyonu tanımlar (format, koşul vb.)' }, { n: 'Handlebars.registerPartial(name, tmpl)', d: 'Yeniden kullanılabilir şablon parçası kaydeder' }, { n: '{{#each items}}', d: 'Dizi üzerinde döngü oluşturur' }], alternatives: ['ejs', 'pug', 'nunjucks'] },

    'pm2': { version: '5.4', license: 'AGPL-3.0', features: ['Cluster modu', 'Load balancing', 'Log yönetimi', 'Startup script', 'Monitoring dashboard', 'Zero-downtime reload'], useCases: ['Üretim deployment', 'Process izleme', 'Otomatik restart', 'Multi-app yönetimi'], keyAPIs: [{ n: 'pm2 start app.js', d: 'Uygulamayı daemon olarak başlatır' }, { n: 'pm2 start app.js -i max', d: 'CPU çekirdek sayısı kadar instance başlatır (cluster)' }, { n: 'pm2 logs', d: 'Tüm uygulamaların log çıktısını gösterir' }, { n: 'pm2 monit', d: 'Gerçek zamanlı CPU/RAM kullanım izleme' }, { n: 'pm2 reload all', d: 'Sıfır kesinti ile tüm uygulamaları yeniden yükler' }, { n: 'ecosystem.config.js', d: 'Çoklu uygulama yapılandırma dosyası' }], alternatives: ['nodemon', 'forever', 'docker'] },

    'date-fns': { version: '4.1', license: 'MIT', features: ['200+ fonksiyon', 'Tree-shaking', 'Immutable', 'Yerelleştirme (Türkçe)', 'TypeScript native', 'FP modülü'], useCases: ['Tarih formatlama', 'Tarih farkı hesaplama', 'Yerelleştirilmiş tarih', 'Zaman dilimi'], keyAPIs: [{ n: 'format(date, pattern)', d: 'Tarihi belirtilen formatta string\'e dönüştürür' }, { n: 'addDays(date, amount)', d: 'Tarihe gün ekler, yeni Date döner' }, { n: 'differenceInDays(a, b)', d: 'İki tarih arasındaki gün farkını hesaplar' }, { n: 'parseISO(string)', d: 'ISO 8601 string\'i Date nesnesine dönüştürür' }, { n: 'isAfter(a, b)', d: 'İlk tarihin ikinciden sonra olup olmadığını kontrol eder' }], alternatives: ['dayjs', 'luxon', 'moment'] },

    'nanoid': { version: '5.0', license: 'MIT', features: ['130 byte boyut', 'URL-dostu ID', 'Kriptografik güvenlik', 'Özel alfabe', 'UUID\'den kısa', 'Async/sync'], useCases: ['Veritabanı ID', 'URL kısaltma', 'Dosya ID', 'Session token'], keyAPIs: [{ n: 'nanoid()', d: '21 karakterlik benzersiz, URL-güvenli ID oluşturur' }, { n: 'nanoid(size)', d: 'Belirtilen uzunlukta ID oluşturur' }, { n: 'customAlphabet(chars, size)', d: 'Özel karakter seti ile ID üretici fonksiyon döner' }, { n: 'urlAlphabet', d: 'URL-güvenli alfabe stringi (A-Za-z0-9_-)' }], alternatives: ['uuid', 'cuid', 'ulid'] },

    'debug': { version: '4.3', license: 'MIT', features: ['Namespace bazlı log', 'Renkli çıktı', 'Çevre değişkeni kontrolü', 'ms zaman damgası', 'Tarayıcı desteği', 'Wildcard eşleşme'], useCases: ['Kütüphane debug log', 'Modül bazlı loglama', 'Geliştirme debug', 'Hata ayıklama'], keyAPIs: [{ n: 'debug(namespace)', d: 'Belirtilen namespace için logger fonksiyonu oluşturur' }, { n: 'DEBUG=app:*', d: 'Çevre değişkeni ile hangi logların görüneceğini belirler' }, { n: 'log(msg, ...args)', d: 'Namespace altında log mesajı yazar' }, { n: 'enabled', d: 'Bu namespace\'in aktif olup olmadığını kontrol eder' }], alternatives: ['pino', 'winston', 'console'] },

    'typeorm': { version: '0.3', license: 'MIT', features: ['Active Record ve Data Mapper', 'Entity dekoratörleri', 'Migration sistemi', 'Query builder', 'Relations', 'Cache'], useCases: ['TypeScript ORM', 'Enterprise uygulama', 'Çoklu veritabanı', 'GraphQL backend'], keyAPIs: [{ n: '@Entity()', d: 'Sınıfı veritabanı tablosuna eşleyen dekoratör' }, { n: '@Column()', d: 'Sınıf özelliğini tablo sütununa eşler' }, { n: '@PrimaryGeneratedColumn()', d: 'Otomatik artan primary key sütunu tanımlar' }, { n: 'repository.find({ where })', d: 'Koşula uyan kayıtları getirir' }, { n: 'repository.save(entity)', d: 'Entity\'yi veritabanına kaydeder veya günceller' }], alternatives: ['prisma', 'sequelize', 'drizzle-orm'] },

    'concurrently': { version: '9.1', license: 'MIT', features: ['Paralel komut çalıştırma', 'Renk kodlu çıktı', 'Önek etiketleri', 'Hata yönetimi', 'Kill others', 'Komut grupları'], useCases: ['Full-stack geliştirme', 'Monorepo script', 'Test paralelleme', 'Multi-service start'], keyAPIs: [{ n: 'concurrently "cmd1" "cmd2"', d: 'İki komutu aynı anda çalıştırır' }, { n: '--kill-others-on-fail', d: 'Bir komut başarısız olursa diğerlerini de durdurur' }, { n: '-n name1,name2', d: 'Her komut için özel isim etiketi belirler' }, { n: '-p prefix', d: 'Çıktı öneki stili: pid, name, command vb.' }], alternatives: ['npm-run-all', 'turbo'] },

    'cross-env': { version: '7.0', license: 'MIT', features: ['Platformlar arası env', 'Windows/Linux/macOS uyumlu', 'Çoklu değişken', 'Komut zincirleme', 'Sıfır yapılandırma'], useCases: ['NODE_ENV ayarlama', 'CI/CD ortam değişkeni', 'Test ortamı', 'Build modu'], keyAPIs: [{ n: 'cross-env NODE_ENV=production cmd', d: 'Ortam değişkeni ayarlar ve komutu çalıştırır' }, { n: 'cross-env VAR1=a VAR2=b cmd', d: 'Birden fazla değişken aynı anda ayarlanabilir' }], alternatives: ['env-cmd', 'dotenv-cli'] },

    'archiver': { version: '7.0', license: 'MIT', features: ['ZIP ve TAR arşiv', 'Stream tabanlı', 'Sıkıştırma seviyesi', 'Dizin ekleme', 'Dosya ekleme', 'Büyük dosya desteği'], useCases: ['Dosya arşivleme', 'Backup oluşturma', 'Download bundle', 'Log arşivi'], keyAPIs: [{ n: 'archiver(format, opts)', d: 'Arşiv oluşturur, "zip" veya "tar" formatı' }, { n: 'archive.directory(path, dest)', d: 'Dizini arşive ekler' }, { n: 'archive.file(path, opts)', d: 'Tek dosya ekler, arşivdeki adı belirlenebilir' }, { n: 'archive.pipe(output)', d: 'Arşivi writable stream\'e yönlendirir' }, { n: 'archive.finalize()', d: 'Arşivi tamamlar ve stream\'i kapatır' }], alternatives: ['adm-zip', 'tar', 'jszip'] },

    'esbuild': { version: '0.24', license: 'MIT', features: ['Go ile yazılmış, 10-100x hızlı', 'JSX/TSX native', 'Tree shaking', 'CSS bundling', 'Source map', 'Watch modu'], useCases: ['Hızlı bundling', 'TypeScript derleme', 'CSS minify', 'Dev sunucu'], keyAPIs: [{ n: 'esbuild.build(opts)', d: 'Dosyaları paketler, opts: entryPoints, outfile, bundle, minify' }, { n: 'esbuild.transform(code, opts)', d: 'Kodu dönüştürür (TS→JS, minify vb.)' }, { n: '--bundle', d: 'Tüm import\'ları tek dosyada birleştirir' }, { n: '--minify', d: 'Kodu küçültür, production için optimize eder' }, { n: '--watch', d: 'Dosya değişikliklerini izler ve otomatik rebuild yapar' }], alternatives: ['webpack', 'rollup', 'swc'] },

    'formidable': { version: '3.5', license: 'MIT', features: ['Form veri ayrıştırma', 'Çoklu dosya yükleme', 'İlerleme takibi', 'Boyut sınırlama', 'Geçici dosya yönetimi', 'Plugin sistemi'], useCases: ['Dosya yükleme API', 'Form işleme', 'Webhook alıcı', 'Medya upload'], keyAPIs: [{ n: 'formidable(opts)', d: 'Form ayrıştırıcı oluşturur, maxFileSize ve uploadDir ayarlanır' }, { n: 'form.parse(req, cb)', d: 'İsteği ayrıştırır, fields ve files döner' }, { n: 'form.on("progress", cb)', d: 'Yükleme ilerlemesini yüzde olarak takip eder' }, { n: 'form.on("file", cb)', d: 'Her dosya yüklendiğinde tetiklenir' }], alternatives: ['multer', 'busboy', 'multiparty'] },

    'mysql2': { version: '3.11', license: 'MIT', features: ['MySQL 8.0 desteği', 'Prepared statement', 'Connection pool', 'Promise API', 'Stream sorgu', 'SSL/TLS'], useCases: ['MySQL CRUD', 'Web uygulama veritabanı', 'Legacy sistem', 'Veri analizi'], keyAPIs: [{ n: 'mysql.createPool(config)', d: 'Bağlantı havuzu oluşturur, max bağlantı sayısı ayarlanır' }, { n: 'pool.execute(sql, params)', d: 'Prepared statement çalıştırır, SQL injection önler' }, { n: 'pool.query(sql)', d: 'Basit SQL sorgusu çalıştırır' }, { n: 'connection.beginTransaction()', d: 'Transaction başlatır, commit/rollback gerektirir' }], alternatives: ['pg', 'better-sqlite3', 'mariadb'] },

    'http-proxy-middleware': { version: '3.0', license: 'MIT', features: ['HTTP proxy', 'WebSocket proxy', 'Path rewriting', 'Hedef değiştirme', 'Event hook\'ları', 'CORS bypass'], useCases: ['API proxy (geliştirme)', 'Mikroservis gateway', 'CORS çözümü', 'Reverse proxy'], keyAPIs: [{ n: 'createProxyMiddleware(opts)', d: 'Proxy middleware oluşturur, target ile hedef sunucu belirlenir' }, { n: 'target', d: 'İsteklerin yönlendirileceği hedef sunucu URL\'si' }, { n: 'pathRewrite', d: 'İstek path\'ini yeniden yazar, prefix kaldırma vb.' }, { n: 'changeOrigin: true', d: 'Origin header\'ı hedef sunucuya uyacak şekilde değiştirir' }], alternatives: ['node-http-proxy', 'express-gateway'] },

    'yup': { version: '1.4', license: 'MIT', features: ['Schema doğrulama', 'Koşullu doğrulama', 'Dönüşüm (cast)', 'TypeScript desteği', 'Formik uyumlu', 'Zincirleme API'], useCases: ['Form validasyonu (React)', 'API şema kontrolü', 'Veri temizleme', 'Konfigürasyon doğrulama'], keyAPIs: [{ n: 'yup.string().required()', d: 'Zorunlu string alanı tanımlar' }, { n: 'yup.object({ ... })', d: 'Nesne şeması oluşturur, alanlar ayrı doğrulanır' }, { n: 'schema.validate(data)', d: 'Veriyi asenkron doğrular, hata fırlatabilir' }, { n: 'schema.cast(data)', d: 'Veriyi şemaya göre dönüştürür (string→number vb.)' }, { n: '.when(field, opts)', d: 'Başka bir alana bağlı koşullu doğrulama kurar' }], alternatives: ['zod', 'joi', 'valibot'] },

    'dotenv-expand': { version: '11.0', license: 'BSD-2', features: ['Değişken genişletme', '${VAR} sözdizimi', 'Varsayılan değer', 'dotenv ile entegre', 'Sıfır bağımlılık'], useCases: ['Ortam değişkeni referansı', 'URL oluşturma', 'Dinamik path', 'Konfigürasyon birleştirme'], keyAPIs: [{ n: 'dotenvExpand.expand(env)', d: 'dotenv.config() sonucundaki ${VAR} referanslarını genişletir' }, { n: '${VAR}', d: 'Mevcut ortam değişkenine referans verir' }, { n: '${VAR:-default}', d: 'Değişken tanımlı değilse varsayılan değer kullanır' }], alternatives: ['dotenv', 'env-cmd'] },

    'sinon': { version: '19.0', license: 'BSD-3', features: ['Spy, Stub, Mock', 'Sahte zamanlayıcı', 'Sahte sunucu', 'Sandbox', 'Assertion helpers', 'Promise desteği'], useCases: ['Fonksiyon izleme', 'Harici servis mock', 'Zaman testi', 'Hata senaryosu'], keyAPIs: [{ n: 'sinon.spy(obj, method)', d: 'Fonksiyon çağrılarını izler, gerçek fonksiyon çalışır' }, { n: 'sinon.stub(obj, method)', d: 'Fonksiyonu sahte ile değiştirir, davranış programlanabilir' }, { n: 'stub.resolves(value)', d: 'Stub\'ın belirtilen değerle resolve eden promise dönmesini sağlar' }, { n: 'sinon.mock(obj)', d: 'Nesne üzerinde beklenti tanımlama, verification yapar' }, { n: 'sinon.restore()', d: 'Tüm spy/stub/mock\'ları orijinaline geri döndürür' }], alternatives: ['jest.fn()', 'testdouble', 'nock'] },

    'swagger-ui-express': { version: '5.0', license: 'MIT', features: ['Swagger UI otomatik oluşturma', 'OpenAPI 3.0', 'İnteraktif test', 'Tema özelleştirme', 'Express middleware', 'Try it out'], useCases: ['API dokümantasyonu', 'Geliştirici portalı', 'API test arayüzü', 'Team iletişim'], keyAPIs: [{ n: 'swaggerUi.serve', d: 'Swagger UI statik dosyalarını sunan middleware' }, { n: 'swaggerUi.setup(spec)', d: 'OpenAPI spec ile Swagger UI\'ı yapılandırır' }, { n: 'swaggerJsdoc(opts)', d: 'JSDoc yorumlarından OpenAPI spec oluşturur' }, { n: '@openapi annotation', d: 'Route üzerine API şeması tanımlayan JSDoc etiketi' }], alternatives: ['redoc', 'stoplight', 'apidog'] },

    'config': { version: '3.3', license: 'MIT', features: ['Hiyerarşik yapılandırma', 'Ortam bazlı dosyalar', 'JSON/YAML/JS desteği', 'Değişken override', 'Immutable config', 'Özel ortam'], useCases: ['Uygulama yapılandırma', 'Ortam bazlı ayarlar', 'Güvenli config yönetimi', 'Mikroservis config'], keyAPIs: [{ n: 'config.get(path)', d: 'Nokta notasyonu ile iç içe yapılandırma değerini okur' }, { n: 'config.has(path)', d: 'Belirtilen yapılandırma yolunun var olup olmadığını kontrol eder' }, { n: 'default.json', d: 'Tüm ortamlar için temel yapılandırma dosyası' }, { n: 'production.json', d: 'Üretim ortamına özel override değerleri' }], alternatives: ['dotenv', 'convict', 'nconf'] },

    'semver': { version: '7.6', license: 'ISC', features: ['Sürüm karşılaştırma', 'Aralık kontrolü', 'Sürüm artırma', 'Ön-release etiket', 'Sıralama', 'npm core'], useCases: ['Bağımlılık yönetimi', 'Sürüm kontrolü', 'CLI sürüm mantığı', 'Plugin uyumluluk'], keyAPIs: [{ n: 'semver.valid(version)', d: 'String\'in geçerli semver olup olmadığını kontrol eder' }, { n: 'semver.gt(v1, v2)', d: 'v1 > v2 ise true döner' }, { n: 'semver.satisfies(version, range)', d: 'Sürümün belirtilen aralığa uyup uymadığını kontrol eder' }, { n: 'semver.inc(version, type)', d: 'major/minor/patch sürümü bir artırır' }, { n: 'semver.coerce(str)', d: 'Gevşek string\'i geçerli semver\'e dönüştürmeye çalışır' }], alternatives: ['compare-versions'] },

    'rimraf': { version: '6.0', license: 'ISC', features: ['Platformlar arası rm -rf', 'Glob desteği', 'Async/sync API', 'Retry mantığı', 'Windows uyumlu', 'Node.js 18+ native'], useCases: ['Build temizleme', 'node_modules silme', 'CI/CD temizlik', 'Geçici dosya silme'], keyAPIs: [{ n: 'rimraf(path)', d: 'Dosya/dizini recursive olarak siler (async)' }, { n: 'rimrafSync(path)', d: 'Senkron versiyon' }, { n: 'rimraf("dist/**")', d: 'Glob kalıbı ile eşleşen dosyaları siler' }], alternatives: ['del', 'fs.rm', 'fs-extra'] },

    'p-limit': { version: '6.1', license: 'MIT', features: ['Promise eşzamanlılık sınırlama', 'Kuyruk yönetimi', 'Aktif sayacı', 'Temizlenebilir kuyruk', 'TypeScript', 'Sıfır bağımlılık'], useCases: ['API rate limit uyumu', 'Dosya işleme sınırlama', 'DB bağlantı limiti', 'Kaynak yönetimi'], keyAPIs: [{ n: 'pLimit(concurrency)', d: 'Eşzamanlılık limiti oluşturur, sayı kadar promise aynı anda çalışır' }, { n: 'limit(fn)', d: 'Fonksiyonu kuyruğa ekler, sıra gelince çalıştırır' }, { n: 'limit.activeCount', d: 'Şu anda çalışan promise sayısını döner' }, { n: 'limit.pendingCount', d: 'Kuyrukta bekleyen promise sayısını döner' }], alternatives: ['p-queue', 'async.eachLimit', 'bottleneck'] },

    'figlet': { version: '1.8', license: 'MIT', features: ['ASCII art metin', '100+ font', 'Yatay layout', 'Senkron ve async', 'Özel genişlik', 'Boşluk ayarı'], useCases: ['CLI hoş geldin mesajı', 'Banner oluşturma', 'Log başlığı', 'Terminal dekorasyon'], keyAPIs: [{ n: 'figlet(text, cb)', d: 'Metni varsayılan fontta ASCII art\'a dönüştürür' }, { n: 'figlet.text(text, { font }, cb)', d: 'Belirtilen font ile ASCII art oluşturur' }, { n: 'figlet.textSync(text)', d: 'Senkron versiyon, doğrudan string döner' }, { n: 'figlet.fonts(cb)', d: 'Kullanılabilir tüm font adlarını listeler' }], alternatives: ['cfonts', 'gradient-string'] },

    'async': { version: '3.2', license: 'MIT', features: ['Paralel ve seri çalıştırma', 'Waterfall akış', 'Kuyruk sistemi', 'Retry mantığı', 'eachLimit', 'mapSeries'], useCases: ['Paralel API çağrıları', 'Sınırlı eşzamanlılık', 'Bağımlı async işlemler', 'Toplu veri işleme'], keyAPIs: [{ n: 'async.parallel(tasks)', d: 'Tüm görevleri aynı anda çalıştırır, tümü bitince sonuç döner' }, { n: 'async.series(tasks)', d: 'Görevleri sırayla çalıştırır, her biri bitmeden sonraki başlamaz' }, { n: 'async.waterfall(tasks)', d: 'Her görevin çıktısı bir sonrakinin girdisi olur' }, { n: 'async.eachLimit(arr, limit, fn)', d: 'Dizi elemanları üzerinde sınırlı paralellikle işlem yapar' }, { n: 'async.queue(worker, concurrency)', d: 'İş kuyruğu oluşturur, concurrency kadar paralel çalışır' }], alternatives: ['p-limit', 'p-queue', 'bluebird'] },

    'connect-mongo': { version: '5.1', license: 'MIT', features: ['MongoDB session store', 'TTL ile otomatik süre dolumu', 'Şifreleme', 'Mongoose/MongoClient desteği', 'Otomatik index', 'Seri/paralel kaydetme'], useCases: ['Oturum saklamak (MongoDB)', 'Ölçeklenebilir session', 'Multi-server oturum', 'Kalıcı oturum'], keyAPIs: [{ n: 'MongoStore.create({ mongoUrl })', d: 'MongoDB bağlantı URL\'si ile session store oluşturur' }, { n: 'ttl', d: 'Oturum süresi (saniye), varsayılan 14 gün' }, { n: 'crypto: { secret }', d: 'Session verisini şifreler' }, { n: 'autoRemove: "native"', d: 'Süresi dolan oturumları MongoDB TTL index ile otomatik siler' }], alternatives: ['connect-redis', 'memorystore'] },

    'nunjucks': { version: '3.2', license: 'BSD-2', features: ['Jinja2 benzeri sözdizimi', 'Şablon kalıtımı', 'Makrolar', 'Filtreler', 'Otomatik kaçış', 'Asenkron destek'], useCases: ['Sunucu taraflı şablon', 'Statik site üretici', 'E-posta şablonu', 'CMS'], keyAPIs: [{ n: 'nunjucks.configure(path, opts)', d: 'Şablon dizinini ve ayarları yapılandırır, Express ile entegre' }, { n: 'nunjucks.render(name, ctx)', d: 'Şablonu veri ile render eder, HTML string döner' }, { n: '{% extends "base.njk" %}', d: 'Başka şablondan kalıtım alır' }, { n: '{% block name %}', d: 'Kalıtımda doldurulacak/override edilecek alan tanımlar' }, { n: '{{ variable | filter }}', d: 'Değişkene filtre uygular (upper, truncate vb.)' }], alternatives: ['ejs', 'pug', 'handlebars'] },

    '@babel/core': { version: '7.26', license: 'MIT', features: ['ES6+ dönüşümü', 'JSX desteği', 'Plugin ekosistemi', 'Preset sistemi', 'Source map', 'Polyfill ekleme'], useCases: ['Eski tarayıcı desteği', 'JSX derleme', 'TypeScript derleme', 'Syntax dönüşümü'], keyAPIs: [{ n: '@babel/preset-env', d: 'Hedef ortama göre gerekli dönüşümleri otomatik uygular' }, { n: 'babel.transformSync(code, opts)', d: 'Kodu belirtilen ayarlarla dönüştürür' }, { n: 'babel.config.json', d: 'Proje genelinde Babel yapılandırma dosyası' }, { n: '@babel/plugin-transform-runtime', d: 'Helper fonksiyonları paylaşarak bundle boyutunu küçültür' }], alternatives: ['esbuild', 'swc', 'tsc'] },

    'rollup': { version: '4.28', license: 'MIT', features: ['ES modül bundler', 'Tree shaking', 'Code splitting', 'Plugin API', 'Multi-output', 'Watch modu'], useCases: ['Kütüphane bundling', 'ES module paket', 'Vite production build', 'Küçük bundle'], keyAPIs: [{ n: 'input', d: 'Giriş dosyası yolu' }, { n: 'output.format', d: 'Çıktı formatı: cjs, esm, umd, iife vb.' }, { n: 'plugins', d: 'Rollup eklentileri: resolve, commonjs, terser vb.' }, { n: 'rollup -c', d: 'rollup.config.js dosyasını kullanarak derleme başlatır' }, { n: 'external', d: 'Bundle dışında tutulacak bağımlılıklar (peer deps vb.)' }], alternatives: ['webpack', 'esbuild', 'parcel'] },

    'mongoose-paginate-v2': { version: '1.8', license: 'MIT', features: ['Kolay pagination', 'Toplam sayfa bilgisi', 'Özel sıralama', 'Select/populate', 'Lean sorgu', 'Özel label'], useCases: ['API sayfalama', 'Tablo sayfalama', 'Arama sonuçları', 'Dashboard listeleme'], keyAPIs: [{ n: 'schema.plugin(mongoosePaginate)', d: 'Şemaya paginate metodunu ekler' }, { n: 'Model.paginate(filter, opts)', d: 'Sayfalanmış sorgu, page ve limit parametreleri' }, { n: 'result.docs', d: 'Mevcut sayfadaki belgeler dizisi' }, { n: 'result.totalPages', d: 'Toplam sayfa sayısı' }, { n: 'result.hasNextPage', d: 'Sonraki sayfa var mı (boolean)' }], alternatives: ['mongoose-aggregate-paginate-v2'] },

    'boxen': { version: '8.0', license: 'MIT', features: ['Terminal kutu çizimi', 'Farklı kenarlık stili', 'Padding/margin', 'Renk desteği', 'Başlık', 'Alignment'], useCases: ['CLI bilgi kutusu', 'Uyarı mesajı', 'Hoş geldin banner', 'Versiyon bildirimi'], keyAPIs: [{ n: 'boxen(text, opts)', d: 'Metin etrafına dekoratif kutu çizer' }, { n: 'borderStyle', d: 'Kenarlık stili: single, double, round, classic vb.' }, { n: 'padding', d: 'İç boşluk ayarı (sayı veya {top,right,bottom,left})' }, { n: 'title', d: 'Kutunun üstünde başlık metni' }, { n: 'borderColor', d: 'Kenarlık rengi: green, red, cyan vb.' }], alternatives: ['cli-boxes', 'terminal-kit'] },

    'moment': { version: '2.30', license: 'MIT', features: ['Tarih/saat işleme', 'Yerelleştirme (Türkçe)', 'Göreceli zaman', 'Duration', 'Calendar', 'Timezone eklentisi'], useCases: ['Legacy proje', 'Tarih formatlama', 'Zaman farkı', 'Takvim fonksiyonları'], keyAPIs: [{ n: 'moment()', d: 'Şu anki tarih/saat ile moment nesnesi oluşturur' }, { n: '.format(pattern)', d: 'Tarihi belirtilen formatta string\'e dönüştürür' }, { n: '.fromNow()', d: 'Göreli zaman döner: "2 saat önce" gibi' }, { n: '.add(value, unit)', d: 'Tarihe süre ekler (gün, ay, yıl vb.)' }, { n: 'moment.duration(value)', d: 'Süre nesnesi oluşturur, humanize() ile okunabilir hale gelir' }], alternatives: ['dayjs', 'date-fns', 'luxon'] },

    'chai': { version: '5.1', license: 'MIT', features: ['BDD: expect/should', 'TDD: assert', 'Eklenti sistemi', 'Zincirleme assertion', 'Deep equality', 'Özel matcher'], useCases: ['Unit test assertion', 'BDD test', 'Mocha ile entegrasyon', 'Özel test kuralları'], keyAPIs: [{ n: 'expect(val).to.equal(x)', d: 'Tam eşitlik kontrolü (===)' }, { n: 'expect(val).to.deep.equal(x)', d: 'Derin nesne eşitliği kontrolü' }, { n: 'expect(val).to.be.a(type)', d: 'Tip kontrolü: string, number, array vb.' }, { n: 'expect(arr).to.include(item)', d: 'Dizide veya stringde eleman aramak' }, { n: 'expect(fn).to.throw()', d: 'Fonksiyonun hata fırlatıp fırlatmadığını kontrol eder' }], alternatives: ['jest expect', 'assert', 'power-assert'] },

    'mongodb': { version: '6.11', license: 'Apache-2.0', features: ['Resmi MongoDB sürücü', 'CRUD işlemleri', 'Aggregation pipeline', 'Change streams', 'GridFS', 'Transaction'], useCases: ['MongoDB doğrudan erişim', 'Düşük seviye DB işlemleri', 'Change stream izleme', 'Büyük dosya saklama'], keyAPIs: [{ n: 'new MongoClient(url)', d: 'MongoDB bağlantısı oluşturur' }, { n: 'client.db(name)', d: 'Belirtilen veritabanına erişim sağlar' }, { n: 'db.collection(name)', d: 'Koleksiyona erişim sağlar, CRUD işlemleri yapılır' }, { n: 'collection.insertOne(doc)', d: 'Tek belge ekler, _id otomatik oluşturulur' }, { n: 'collection.find(filter)', d: 'Filtreye uyan belgeleri cursor olarak döner' }], alternatives: ['mongoose', 'prisma'] },

    'playwright': { version: '1.49', license: 'Apache-2.0', features: ['Chromium/Firefox/WebKit', 'Auto-wait', 'Network interception', 'Video kayıt', 'Trace viewer', 'Codegen'], useCases: ['E2E test', 'Çapraz tarayıcı test', 'Web scraping', 'Visual regression'], keyAPIs: [{ n: 'chromium.launch()', d: 'Chromium tarayıcı başlatır' }, { n: 'page.goto(url)', d: 'URL\'ye gider, sayfa yüklenene kadar bekler' }, { n: 'page.locator(selector)', d: 'Element seçer, otomatik bekleme yapar' }, { n: 'page.fill(selector, text)', d: 'Input alanına metin yazar' }, { n: 'expect(locator).toBeVisible()', d: 'Elementin görünür olduğunu doğrular' }, { n: 'page.screenshot()', d: 'Sayfanın ekran görüntüsünü alır' }], alternatives: ['puppeteer', 'cypress', 'selenium'] },

    'cors-anywhere': { version: '0.4', license: 'MIT', features: ['CORS proxy sunucusu', 'Origin whitelist', 'Header temizleme', 'Rate limiting', 'HTTPS desteği', 'Geliştirme aracı'], useCases: ['CORS bypass (geliştirme)', '3. parti API proxy', 'Test ortamı', 'Prototipleme'], keyAPIs: [{ n: 'corsAnywhere.createServer(opts)', d: 'Proxy sunucusu oluşturur' }, { n: 'originWhitelist', d: 'İzin verilen origin listesi, boş = hepsine izin' }, { n: 'requireHeader', d: 'Zorunlu headerlar, istismar azaltma için' }, { n: '.listen(port)', d: 'Proxy\'yi belirtilen portta başlatır' }], alternatives: ['http-proxy-middleware', 'cors'] },

    'agenda': { version: '5.0', license: 'MIT', features: ['MongoDB tabanlı zamanlayıcı', 'Cron ve interval', 'İş önceliklendirme', 'Eşzamanlılık kontrolü', 'İş kilitleme', 'Dashboard'], useCases: ['Zamanlanmış e-posta', 'Rapor oluşturma', 'Veri temizleme', 'Arka plan işleri'], keyAPIs: [{ n: 'agenda.define(name, fn)', d: 'İş tipini tanımlar, fn işçi fonksiyonudur' }, { n: 'agenda.every(interval, name)', d: 'Tekrarlayan görev oluşturur (cron veya insan-okunabilir)' }, { n: 'agenda.schedule(when, name, data)', d: 'Belirli bir zamanda tek seferlik iş planlar' }, { n: 'agenda.start()', d: 'Zamanlayıcıyı başlatır, işleri çalıştırmaya başlar' }, { n: 'job.attrs.data', d: 'İşe bağlı veri nesnesine erişir' }], alternatives: ['bull', 'node-cron', 'bree'] },

    'rate-limiter-flexible': { version: '5.0', license: 'ISC', features: ['Redis/Mongo/bellek backend', 'DDoS koruması', 'Sliding window', 'Block stratejisi', 'Cluster desteği', 'Insurance limiter'], useCases: ['Login koruması', 'API rate limit', 'DDoS önleme', 'Kaynak koruma'], keyAPIs: [{ n: 'new RateLimiterMemory({ points, duration })', d: 'Bellekte çalışan limiter, noktalar sürede tüketilir' }, { n: 'new RateLimiterRedis(opts)', d: 'Redis backed limiter, çoklu sunucu için uygun' }, { n: 'limiter.consume(key)', d: 'Bir istek tüketir, limit aşılırsa hata fırlatır' }, { n: 'limiter.block(key, duration)', d: 'Key\'i belirtilen süre boyunca tamamen bloklar' }], alternatives: ['express-rate-limit', 'bottleneck'] },

    'rxjs': { version: '7.8', license: 'Apache-2.0', features: ['Observable stream', '200+ operator', 'Subject tipleri', 'Scheduler', 'Pipe API', 'Angular core'], useCases: ['Reaktif veri akışı', 'Event yönetimi', 'WebSocket stream', 'Gerçek zamanlı arama'], keyAPIs: [{ n: 'from(source)', d: 'Array, Promise veya iterable\'dan Observable oluşturur' }, { n: 'interval(ms)', d: 'Belirtilen aralıkta sayı yayan Observable oluşturur' }, { n: '.pipe(operators)', d: 'Observable\'a operatör zinciri uygular' }, { n: 'map(fn)', d: 'Her değeri dönüştürür' }, { n: 'filter(fn)', d: 'Koşula uymayan değerleri filtreler' }, { n: 'subscribe(observer)', d: 'Observable\'ı dinlemeye başlar, değerler geldiğinde callback çalışır' }], alternatives: ['bacon.js', 'most', 'xstream'] },

    'dotenv-safe': { version: '9.1', license: 'MIT', features: ['.env.example ile doğrulama', 'Eksik değişken tespiti', 'Erken hata yakalama', 'dotenv tabanlı', 'Özel örnek dosya', 'CI güvenliği'], useCases: ['Ortam doğrulama', 'CI/CD güvenlik', 'Takım geliştirme', 'Deployment kontrolü'], keyAPIs: [{ n: 'require("dotenv-safe").config()', d: '.env dosyasını yükler ve .env.example ile doğrular' }, { n: '.env.example', d: 'Gerekli tüm değişkenlerin listesini içeren referans dosyası' }, { n: 'allowEmptyValues', d: 'Boş değerlere izin verir (varsayılan: false)' }, { n: 'MissingEnvVarsError', d: 'Eksik değişken olduğunda fırlatılan hata tipi' }], alternatives: ['dotenv', 'envalid', 'env-schema'] },

    'passport-jwt': { version: '4.0', license: 'MIT', features: ['JWT strateji', 'Bearer token', 'Header/query/cookie', 'Custom extractor', 'Payload doğrulama', 'Passport uyumlu'], useCases: ['Stateless API auth', 'Bearer token doğrulama', 'Mikroservis güvenlik', 'SPA auth'], keyAPIs: [{ n: 'new JwtStrategy(opts, verify)', d: 'JWT stratejisi oluşturur, token çıkarma ve doğrulama ayarları' }, { n: 'ExtractJwt.fromAuthHeaderAsBearerToken()', d: 'Authorization header\'dan Bearer token çıkarır' }, { n: 'secretOrKey', d: 'Token doğrulama için kullanılan gizli anahtar' }, { n: 'jwtFromRequest', d: 'Token\'ın istekten nasıl çıkarılacağını belirler' }], alternatives: ['express-jwt', 'jose', 'jsonwebtoken'] },

    'connect-flash': { version: '0.1', license: 'MIT', features: ['Flash mesajları', 'Tek seferlik bildirim', 'Session tabanlı', 'Express uyumlu', 'Çoklu mesaj tipi', 'Redirect desteği'], useCases: ['Login hata mesajı', 'Başarı bildirimi', 'Form hata gösterme', 'İşlem onayı'], keyAPIs: [{ n: 'req.flash(type, message)', d: 'Session\'a flash mesaj yazar, redirect sonrası okunur' }, { n: 'req.flash(type)', d: 'Belirtilen tipteki flash mesajları okur ve siler' }, { n: 'req.flash()', d: 'Tüm flash mesajlarını nesne olarak döner' }], alternatives: ['express-flash', 'express-messages'] },

    'eslint': { version: '9.16', license: 'MIT', features: ['JavaScript/TypeScript lint', 'Flat config', 'Auto-fix', 'Plugin ekosistemi', 'Özel kurallar', 'IDE entegrasyon'], useCases: ['Kod kalitesi kontrolü', 'CI/CD lint', 'Takım standartları', 'Hata önleme'], keyAPIs: [{ n: 'eslint.config.js', d: 'Flat config formatında lint yapılandırma dosyası' }, { n: 'npx eslint src/', d: 'Belirtilen dizindeki dosyaları tarar' }, { n: 'npx eslint --fix', d: 'Otomatik düzeltilebilen sorunları düzeltir' }, { n: 'rules: { ... }', d: 'Lint kuralları: error, warn, off seviyeleri' }, { n: 'plugins', d: 'Ek lint kuralları sağlayan eklentiler (React, TypeScript vb.)' }], alternatives: ['biome', 'oxlint', 'prettier'] },

    'prettier': { version: '3.4', license: 'MIT', features: ['Opinionated formatter', '20+ dil desteği', 'IDE entegrasyon', 'Git hook uyumlu', 'Tutarlı çıktı', 'Ignore dosyası'], useCases: ['Kod formatlama', 'CI/CD format kontrolü', 'Pre-commit hook', 'Takım standardı'], keyAPIs: [{ n: '.prettierrc', d: 'Formatlama ayarları: semi, singleQuote, tabWidth vb.' }, { n: 'npx prettier --write src/', d: 'Dosyaları otomatik formatlar' }, { n: 'npx prettier --check src/', d: 'Format hatası olan dosyaları listeler (CI için)' }, { n: 'singleQuote: true', d: 'Tek tırnak kullanımını zorunlu kılar' }, { n: 'trailingComma: "es5"', d: 'ES5 uyumlu yerlerde trailing comma ekler' }], alternatives: ['biome', 'dprint', 'standardjs'] },

    'husky': { version: '9.1', license: 'MIT', features: ['Git hooks yönetimi', 'Pre-commit hook', 'Pre-push hook', 'lint-staged uyumlu', 'Sıfır bağımlılık', 'Modern yapı'], useCases: ['Pre-commit lint', 'Pre-push test', 'Commit message kontrolü', 'Otomatik format'], keyAPIs: [{ n: 'npx husky init', d: 'Projeye husky kurulumu yapar, .husky dizini oluşturur' }, { n: '.husky/pre-commit', d: 'Commit öncesi çalışacak komutları içeren hook dosyası' }, { n: '.husky/pre-push', d: 'Push öncesi çalışacak komutları içeren hook dosyası' }, { n: 'npx lint-staged', d: 'Sadece stage\'lenmiş dosyalarda lint çalıştırır (husky ile kullanılır)' }], alternatives: ['lefthook', 'simple-git-hooks'] }
};
